[project]
name = "hud-overlay"
version = "0.2.1"
description = "Visualizador grÃ¡fico de entradas tipo arcade para joystick o teclado,"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]
